spring.application.name=gateway

server.port=8080

# Eureka Discovery Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=gateway
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Optional: Gateway logging
logging.level.org.springframework.cloud.gateway=INFO